"""Self-consistency check for price_option_from_parameters against a fixed illustrative
parameter set (not the real grader's THEO answer key -- see _world.py). Expected values below
were generated by running the pricer itself against these made-up parameters, so this guards
against regressions in the pricer, not against the actual grader's reference values."""
import math
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from Bot import (
    MarketMaker, MarketParameters, BinaryOption, OptionLeg, Underlying,
    FED_FUNDS_RATE_UNDERLYING_ID, AJARAI_UNDERLYING_ID, THERIODIC_UNDERLYING_ID,
)

PARAMS = MarketParameters(
    ajarai_drift=0.0008, ajarai_idio_std_dev=0.015, ajarai_rate_beta=-0.01, ajarai_sector_beta=0.9,
    rate_down_probability=0.15, rate_reversion_strength=0.2, rate_up_probability=0.2,
    sector_std_dev=0.025, theriodic_drift=0.0012, theriodic_idio_std_dev=0.014,
    theriodic_rate_beta=-0.02, theriodic_sector_beta=1.1, rate_step=0.25, rate_target=2.5,
)

UNDERLYINGS = [
    Underlying(name="FED", underlying_id=FED_FUNDS_RATE_UNDERLYING_ID, value=2.5),
    Underlying(name="AJR", underlying_id=AJARAI_UNDERLYING_ID, value=450.0),
    Underlying(name="THR", underlying_id=THERIODIC_UNDERLYING_ID, value=550.0),
]

CONTRACTS = [
    (BinaryOption(legs=(OptionLeg(FED_FUNDS_RATE_UNDERLYING_ID, 1.0),), option_id=1, steps_until_expiry=1, strike=2.50), 0.8500),
    (BinaryOption(legs=(OptionLeg(FED_FUNDS_RATE_UNDERLYING_ID, 1.0),), option_id=2, steps_until_expiry=5, strike=3.00), 0.1102),
    (BinaryOption(legs=(OptionLeg(AJARAI_UNDERLYING_ID, 1.0),), option_id=3, steps_until_expiry=1, strike=450.00), 0.5099),
    (BinaryOption(legs=(OptionLeg(THERIODIC_UNDERLYING_ID, 1.0),), option_id=4, steps_until_expiry=10, strike=580.00), 0.3310),
    (BinaryOption(legs=(OptionLeg(THERIODIC_UNDERLYING_ID, 1.0), OptionLeg(AJARAI_UNDERLYING_ID, -1.0)), option_id=5, steps_until_expiry=1, strike=0.00), 1.0000),
    (BinaryOption(legs=(OptionLeg(THERIODIC_UNDERLYING_ID, 1.0), OptionLeg(AJARAI_UNDERLYING_ID, -1.0)), option_id=6, steps_until_expiry=10, strike=0.00), 1.0000),
]


def main():
    mm = MarketMaker(UNDERLYINGS, [c for c, _ in CONTRACTS], 10.0)
    max_err = 0.0
    for option, expected in CONTRACTS:
        got = mm.price_option_from_parameters(PARAMS, option)
        err = abs(got - expected)
        max_err = max(max_err, err)
        print(f"{option}: got={got:.4f} expected={expected:.4f} err={err:.6f}")
    print(f"max_error={max_err:.6f}")
    assert max_err < 1e-4, f"THEO max_error {max_err} exceeds 1e-4"
    print("PASS")


if __name__ == "__main__":
    main()
